apiVersion: api.my.domain/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler
    app.kubernetes.io/instance: scaler-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 5 # AM utc
  end: 20 # PM utc
  replicas: 5
  deployments: 
  - name: nginx
    namespace: default

----------

apiVersion: api.my.domain/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler
    app.kubernetes.io/instance: scaler-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 21 # PM utc
  end: 4 # AM utc
  replicas: 1
  deployments: 
  - name: nginx
    namespace: default