apiVersion: my.domain/v1alpha1
kind: Helmer
metadata:
  labels:
    app.kubernetes.io/name: helmer
    app.kubernetes.io/instance: helmer-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: helmer-sample
spec:
  chart: yees-0.1.0.tgz
  releaseName: yees-release
  operation: upgrade
  # TODO(user): Add fields here
